package dev.phonegate.protocol

import org.json.JSONObject
import org.junit.Assert.assertArrayEquals
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertTrue
import org.junit.Assert.fail
import org.junit.BeforeClass
import org.junit.Test
import java.io.File
import java.math.BigInteger

/**
 * Asserts every entry of the shared vectors `protocol/vectors/v1.json` (generated by
 * `crates/pg-core/tests/vectors.rs`), read in place from the repository.
 */
class ProtocolVectorsTest {
    companion object {
        lateinit var v: JSONObject

        @BeforeClass
        @JvmStatic
        fun load() {
            val path = System.getProperty("pg.vectors") ?: error("pg.vectors system property not set")
            val f = File(path)
            assertTrue("vectors missing at $path", f.isFile)
            v = JSONObject(f.readText(Charsets.UTF_8))
            assertEquals(1, v.getInt("version"))
        }

        fun h(section: String, key: String): ByteArray = v.getJSONObject(section).getString(key).unhex()
        fun s(section: String, key: String): String = v.getJSONObject(section).getString(key)

        // --- tiny affine P-256 scalar multiplication, test-only, to derive pubs from scalars ---
        private val p = Crypto.P
        private val a = p.subtract(BigInteger.valueOf(3))
        private val g = Pair(
            BigInteger("6b17d1f2e12c4247f8bce6e563a440f277037d812deb33a0f4a13945d898c296", 16),
            BigInteger("4fe342e2fe1a7f9b8ee7eb4a7c0f9e162bce33576b315ececbb6406837bf51f5", 16),
        )

        private fun add(P1: Pair<BigInteger, BigInteger>?, P2: Pair<BigInteger, BigInteger>?): Pair<BigInteger, BigInteger>? {
            if (P1 == null) return P2
            if (P2 == null) return P1
            val (x1, y1) = P1
            val (x2, y2) = P2
            val lambda = if (x1 == x2) {
                if (y1.add(y2).mod(p).signum() == 0) return null
                x1.multiply(x1).multiply(BigInteger.valueOf(3)).add(a).multiply(y1.shiftLeft(1).modInverse(p)).mod(p)
            } else {
                y2.subtract(y1).multiply(x2.subtract(x1).modInverse(p)).mod(p)
            }
            val x3 = lambda.multiply(lambda).subtract(x1).subtract(x2).mod(p)
            val y3 = lambda.multiply(x1.subtract(x3)).subtract(y1).mod(p)
            return Pair(x3, y3)
        }

        fun pubFromScalar(scalar: ByteArray): ByteArray {
            val k = BigInteger(1, scalar)
            var r: Pair<BigInteger, BigInteger>? = null
            for (i in k.bitLength() - 1 downTo 0) {
                r = add(r, r)
                if (k.testBit(i)) r = add(r, g)
            }
            val (x, y) = r!!
            return byteArrayOf(4) + Crypto.fixed32(x) + Crypto.fixed32(y)
        }

        fun signer(role: String): SoftSigner =
            SoftSigner(Crypto.privateFromScalar(h("keys", "${role}_priv")), h("keys", "${role}_pub"))

        fun qr(): PairingQr = PairingQr.parse(s("pairing", "qr_uri"))
    }

    @Test
    fun encodingSample() {
        val e = Enc("phonegate/v1/test").bytes(byteArrayOf(1, 2, 3)).str("hé").u64(0x0102030405060708L)
            .list(listOf("a".toByteArray(), ByteArray(0))).finish()
        assertEquals(s("encoding", "sample_hex"), e.hex())
        val f = Enc.decode(e, "phonegate/v1/test", 5)
        assertArrayEquals(byteArrayOf(1, 2, 3), f.bytes(1))
        assertEquals("hé", f.string(2))
        assertEquals(0x0102030405060708L, f.u64(3))
        val l = f.list(4)
        assertEquals(2, l.size)
        assertArrayEquals("a".toByteArray(), l[0])
        assertEquals(0, l[1].size)
    }

    @Test
    fun hkdfAndHmac() {
        assertEquals(s("hkdf", "okm"), Crypto.hkdf(h("hkdf", "ikm"), h("hkdf", "salt"), h("hkdf", "info")).hex())
        assertEquals(s("hmac", "tag"), Crypto.hmac(h("hmac", "key"), h("hmac", "msg")).hex())
        assertTrue(Crypto.hmacVerify(h("hmac", "key"), h("hmac", "msg"), h("hmac", "tag")))
        val bad = h("hmac", "tag").also { it[31] = (it[31].toInt() xor 1).toByte() }
        assertFalse(Crypto.hmacVerify(h("hmac", "key"), h("hmac", "msg"), bad))
    }

    @Test
    fun rfcKnownAnswers() {
        // RFC 5869 case 1 and RFC 4231 case 2 guard the HKDF/HMAC plumbing independently.
        val okm = Crypto.hkdf(
            "0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b".unhex(),
            "000102030405060708090a0b0c".unhex(),
            "f0f1f2f3f4f5f6f7f8f9".unhex(),
        )
        assertEquals("3cb25f25faacd57a90434f64d0362f2a2d2d0a90cf1a5a4c5db02d56ecc4c5bf", okm.hex())
        assertEquals(
            "5bdcc146bf60754e6a042426089575c75a003f089d2739839dec58b964ec3843",
            Crypto.hmac("Jefe".toByteArray(), "what do ya want for nothing?".toByteArray()).hex(),
        )
        // NIST GCM test case 16 (AES-256 with AAD).
        val ct = Crypto.aeadSeal(
            "feffe9928665731c6d6a8f9467308308feffe9928665731c6d6a8f9467308308".unhex(),
            "cafebabefacedbaddecaf888".unhex(),
            "d9313225f88406e5a55909c5aff5269a86a7a9531534f7da2e4c303d8a318a721c3c0c95956809532fcf0e2449a6b525b16aedf5aa0de657ba637b39".unhex(),
            "feedfacedeadbeeffeedfacedeadbeefabaddad2".unhex(),
        )
        assertEquals(
            "522dc1f099567d07f47f37a32a84427d643a8cdcbfe5c0c97598a2bd2555d1aa8cb08e48590dbb3da7b08b1056828838c5f61e6393ba7a0abcc9f66276fc6ece0f4e1768cddf8853bb2d551b",
            ct.hex(),
        )
    }

    @Test
    fun keys() {
        for (role in listOf("pc", "device", "approve", "pc_eph", "phone_eph")) {
            val pub = h("keys", "${role}_pub")
            assertArrayEquals("pub of $role", pub, pubFromScalar(h("keys", "${role}_priv")))
            Crypto.parsePub(pub)
        }
        assertEquals(s("keys", "pc_id"), Crypto.idOf(h("keys", "pc_pub")).hex())
        assertEquals(s("keys", "phone_id"), Crypto.idOf(h("keys", "device_pub")).hex())
        // A JCA signature from the scalar verifies against the vector pub (wire form r‖s).
        val sig = signer("device").sign("msg".toByteArray())
        Crypto.verify(h("keys", "device_pub"), "msg".toByteArray(), sig)
    }

    @Test
    fun pairingDerivations() {
        val q = qr()
        assertEquals("https://relay.example.com", q.relayUrl)
        assertEquals("Desk PC", q.pcName)
        assertArrayEquals(h("pairing", "pairing_id"), q.pairingId)
        assertArrayEquals(h("pairing", "psk"), q.psk)
        assertArrayEquals(h("keys", "pc_id"), q.pcPubHash)
        assertEquals(s("pairing", "qr_uri"), q.toUri())
        assertEquals(s("pairing", "slot"), PairingKdf.slot(q.pairingId).hex())
        assertEquals(s("pairing", "k_join"), PairingKdf.kJoin(q.psk, q.pairingId).hex())
        assertEquals(s("pairing", "attest_challenge"), PairingKdf.attestChallenge(q.psk, q.pairingId).hex())
    }

    @Test
    fun pairingFullPhoneRole() {
        val q = qr()
        val now = v.getJSONObject("pairing").getLong("offer_now")
        val offer = PairOffer.verify(h("pairing", "offer_payload"), q, now)
        assertArrayEquals(h("keys", "pc_pub"), offer.pcPub)
        assertArrayEquals(h("keys", "pc_eph_pub"), offer.pcEphPub)
        assertEquals("Desk PC", offer.pcName)

        val phoneName = s("pairing", "phone_name")
        val th = PairingKdf.transcript(
            q.pairingId, offer.pcPub, offer.pcEphPub, offer.pcName,
            h("keys", "device_pub"), h("keys", "approve_pub"), h("keys", "phone_eph_pub"), phoneName,
        )
        assertEquals(s("pairing", "transcript"), th.hex())

        val eph = EphemeralKey.fromScalar(h("keys", "phone_eph_priv"), h("keys", "phone_eph_pub"))
        val shared = eph.agree(offer.pcEphPub)
        assertEquals(s("pairing", "ecdh_shared"), shared.hex())
        // Symmetric check from the PC side.
        val pcEph = EphemeralKey.fromScalar(h("keys", "pc_eph_priv"), h("keys", "pc_eph_pub"))
        assertArrayEquals(shared, pcEph.agree(h("keys", "phone_eph_pub")))

        val kPair = PairingKdf.kPair(shared, q.psk, th)
        assertEquals(s("pairing", "k_pair"), kPair.hex())
        assertEquals(s("pairing", "sas"), PairingKdf.sas(kPair))
        assertEquals(s("pairing", "join_sig_bytes"), PairingKdf.joinSigBytes(th).hex())
        assertEquals(s("pairing", "k_offline"), PairingKdf.kOffline(kPair).hex())

        // join_inner: signatures in the vector are RFC 6979 deterministic; verify them, then
        // re-encode with our encoder and require exact bytes.
        val inner = h("pairing", "join_inner")
        val f = Enc.decode(inner, "phonegate/v1/pair-join-body", 10)
        val sigDev = f.fixed(8, 64)
        val sigApp = f.fixed(9, 64)
        Crypto.verify(h("keys", "device_pub"), PairingKdf.joinSigBytes(th), sigDev)
        Crypto.verify(h("keys", "approve_pub"), PairingKdf.joinSigBytes(th), sigApp)
        val join = PairJoin(
            q.pairingId, h("keys", "device_pub"), h("keys", "approve_pub"), h("keys", "phone_eph_pub"), phoneName,
            listOf(byteArrayOf(0x30, 0x00)), emptyList(), sigDev, sigApp,
        )
        assertEquals(inner.hex(), join.encodeInner().hex())
        assertEquals(s("pairing", "join_payload"), join.seal(q.psk, h("pairing", "join_nonce")).hex())

        // The phone state machine produces the same payload with the same inputs.
        val pp = PhonePairing(q)
        pp.acceptOffer(h("pairing", "offer_payload"), now)
        val prepared = pp.prepare(h("keys", "device_pub"), h("keys", "approve_pub"), eph, phoneName)
        assertEquals(s("pairing", "sas"), prepared.sas)
        val payload = pp.buildJoin(listOf(byteArrayOf(0x30, 0x00)), emptyList(), sigDev, sigApp, h("pairing", "join_nonce"))
        assertEquals(s("pairing", "join_payload"), payload.hex())
        assertEquals(s("pairing", "confirm_phone_payload"), pp.confirm().hex())
        val result = pp.handleComplete(h("pairing", "complete_pc_payload"))
        assertArrayEquals(kPair, result.kPair)
        assertArrayEquals(h("keys", "pc_pub"), result.pcPub)
        assertEquals("https://relay.example.com", result.relayUrl)

        assertEquals(
            s("pairing", "complete_pc_payload"),
            PairingKdf.encodeConfirm(PairingKdf.COMPLETE_LABEL, PairingKdf.confirmMac(kPair, "pc", th)).hex(),
        )
    }

    @Test
    fun approvalRequestAndResponse() {
        val pcPub = h("keys", "pc_pub")
        val devPub = h("keys", "device_pub")
        val appPub = h("keys", "approve_pub")
        val pcId = h("keys", "pc_id")
        val phoneId = h("keys", "phone_id")
        val kPair = h("pairing", "k_pair")

        val reqPlain = h("approval", "request_plain")
        val req = ApprovalRequest.decode(reqPlain)
        assertEquals(42L, req.matchNumber)
        assertEquals("DESK\\owner", req.account)
        assertEquals("Desk PC", req.pcName)
        assertEquals("", req.remoteAddr)
        assertEquals(Scenario.Unlock, req.scenario)
        assertEquals(1_700_000_000_000L, req.issuedAt)
        assertEquals(1_700_000_060_000L, req.expiresAt)
        assertArrayEquals(reqPlain, req.encode())
        assertEquals(s("approval", "request_digest"), req.digest().hex())

        val env = Envelope.parse(h("approval", "request_envelope"))
        assertEquals(Kind.ApprovalRequest, env.kind)
        assertArrayEquals(reqPlain, env.open(pcPub, kPair, Dir.PcToPhone, pcId, phoneId))
        assertEquals(s("approval", "request_envelope"), env.encode().hex())
        // Wire wrapping.
        assertEquals(s("approval", "request_wire"), Wire.wire(Kind.ApprovalRequest, env.encode()).hex())
        val (k, p) = Wire.unwire(h("approval", "request_wire"))
        assertEquals(Kind.ApprovalRequest, k)
        assertArrayEquals(h("approval", "request_envelope"), p)
        // Through the inbox, as the relay service would.
        val ctx = PairingContext(pcPub, kPair, phoneId)
        val inbound = Inbox.receive(ctx, pcId, h("approval", "request_wire"), 1_700_000_001_000L, MemoryReplayGuard())
        assertTrue(inbound is Inbound.Request)
        assertEquals(42L, (inbound as Inbound.Request).request.matchNumber)

        // Decision bytes.
        val db = decisionSignedBytes(req.digest(), Decision.Approve, 42, 1_700_000_010_000L)
        assertEquals(s("approval", "response_decision_bytes"), db.hex())

        // Response plaintext: decode, verify decision signature with the approve key.
        val respPlain = h("approval", "response_plain")
        val resp = ApprovalResponse.decode(respPlain)
        assertEquals(Decision.Approve, resp.decision)
        assertEquals(42L, resp.typedNumber)
        assertArrayEquals(respPlain, resp.encode())
        resp.verifyDecision(appPub, devPub)
        // Approve signed by the approve key must NOT verify as the device key's decision.
        try {
            resp.verifyDecision(devPub, devPub)
            fail("approve decision verified with device key")
        } catch (e: ProtocolException.Verify) { /* expected */ }

        // Response envelope: open as the PC would, then re-seal with same msg_id/nonce.
        val renv = Envelope.parse(h("approval", "response_envelope"))
        assertArrayEquals(respPlain, renv.open(devPub, kPair, Dir.PhoneToPc, phoneId, pcId))
        val resealed = Envelope.parse(
            Envelope.sealWith(kPair, Dir.PhoneToPc, Kind.ApprovalResponse, phoneId, pcId, signer("device"), respPlain, renv.msgId, renv.nonce),
        )
        assertArrayEquals("ciphertext must be byte-identical", renv.ct, resealed.ct)
        assertArrayEquals(renv.msgId, resealed.msgId)
        assertArrayEquals(renv.nonce, resealed.nonce)
        // Our (randomized) signature verifies as the PC would check it.
        assertArrayEquals(respPlain, resealed.open(devPub, kPair, Dir.PhoneToPc, phoneId, pcId))

        // Our own response built with the approve key is accepted by the PC-side check.
        val ours = ApprovalResponse(req.digest(), Decision.Approve, 42, 1_700_000_010_000L, signer("approve").sign(db))
        ours.verifyDecision(appPub, devPub)
    }

    @Test
    fun offline() {
        val pcPub = h("keys", "pc_pub")
        val qrText = s("offline", "qr")
        assertArrayEquals(h("keys", "pc_id"), OfflineChallenge.peekPcId(qrText))
        val c = OfflineChallenge.parseQr(qrText, pcPub, 1_700_000_000_000L)
        assertEquals(s("offline", "challenge_body"), c.body().hex())
        assertEquals(Scenario.Logon, c.scenario)
        assertEquals("DESK\\owner", c.account)
        val code = c.responseCode(h("pairing", "k_offline"))
        assertEquals(s("offline", "code"), code)
        assertEquals(10, code.length)
    }

    @Test
    fun relayAuth() {
        val challenge = h("relay_auth", "challenge")
        assertEquals(s("relay_auth", "signed_bytes"), RelayClient.authBytes(challenge).hex())
        assertEquals("wss://r.example/v1/ws", RelayClient.wsUrl("https://r.example"))
        assertEquals("wss://r.example/pg/v1/ws", RelayClient.wsUrl("https://r.example/pg/"))
        assertEquals("ws://127.0.0.1:8080/v1/ws", RelayClient.wsUrl("http://127.0.0.1:8080"))
        assertNotNull(runCatching { RelayClient.wsUrl("ftp://x") }.exceptionOrNull())
    }
}
